# Generated by Django 3.0.8 on 2020-09-03 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان')),
                ('cover', models.ImageField(upload_to='media/article_cover/', verbose_name='عکس مقاله')),
                ('content', models.TextField(verbose_name='متن مقاله')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('م', 'منتشر شده'), ('پ', 'پیش نویس'), ('د', 'در صف انتشار'), ('ب', 'برگشت داده شده')], default='پ', max_length=1, verbose_name='وضعیت')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='انتشار دهنده')),
            ],
            options={
                'verbose_name': 'توضیحات فیلم آموزشی',
                'verbose_name_plural': ' توضیحات فیلم های آموزشی',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/video/', verbose_name='فیلم')),
                ('description', models.CharField(max_length=400, verbose_name='توضیحات')),
                ('sds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_film.Article')),
            ],
            options={
                'verbose_name': 'فیلم ',
                'verbose_name_plural': 'فیلم ها',
            },
        ),
    ]
