# Generated by Django 3.0.8 on 2020-09-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_film', '0002_auto_20200908_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='sds',
            new_name='article',
        ),
    ]
