# Generated by Django 3.0.8 on 2020-09-08 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycollections', '0002_auto_20190213_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontitle',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_titlces', to='mycollections.Collection'),
        ),
    ]
